FROM python:3.7

RUN apt-get update 
RUN apt-get install python3-pip -y

RUN pip3 install flask
RUN pip3 install flask-sqlalchemy
RUN pip3 install SQLAlchemy
RUN pip3 install pymysql
RUN pip3 install pandas
RUN pip3 install Pillow
